services:
  qdrant:
    image: qdrant/qdrant
    container_name: rekindle-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - rekindle-network
    restart: unless-stopped

volumes:
  qdrant-storage:
    name: qdrant-storage

networks:
  rekindle-network:
    driver: bridge