services:
  qdrant:
    image: qdrant/qdrant
    container_name: rekindle-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${USERPROFILE}/.rekindle/search/qdrant:/qdrant/storage
    networks:
      - rekindle-network
    restart: unless-stopped

networks:
  rekindle-network:
    driver: bridge